### ISSUE TITLE
CLI: multiple values for keyword argument 'cmd' when using 'exec_commands'

### ISSUE THREAD

**Issue by ambsw-technology** [merll/docker-map#16]
I'm trying to run a build script using exec_commands.  I'm getting the following error:

```
Traceback (most recent call last):
  File "/mnt/data/.virtualenvs/build_deploy/local/lib/python2.7/site-packages/fabric/main.py", line 756, in main
    *args, **kwargs
  File "/mnt/data/.virtualenvs/build_deploy/local/lib/python2.7/site-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/mnt/data/.virtualenvs/build_deploy/local/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/data/apex-server/build_deploy/src/fabfile.py", line 612, in app_setup
    apex.workflow_add(config=config, tag=tag)
  File "/data/apex-server/build_deploy/src/helpers/apex.py", line 66, in workflow_add
    workflow_containers_add(config, tag)
  File "/data/apex-server/build_deploy/src/helpers/apex.py", line 402, in workflow_containers_add
    docker.startup_required_containers(docker_map)
  File "/data/apex-server/build_deploy/src/helpers/docker.py", line 125, in startup_required_containers
    container_fabric_inst.startup(container)
  File "/mnt/data/.virtualenvs/build_deploy/local/lib/python2.7/site-packages/dockermap/map/client.py", line 224, in startup
    return self.run_actions('startup', container, instances=instances, map_name=map_name, **kwargs)
  File "/mnt/data/.virtualenvs/build_deploy/local/lib/python2.7/site-packages/dockermap/map/client.py", line 110, in run_actions
    results.extend(runner.run_actions(*actions))
  File "/mnt/data/.virtualenvs/build_deploy/local/lib/python2.7/site-packages/dockermap/map/runner/__init__.py", line 94, in run_actions
    res = c_method(action_config, container_name, **action.extra_data)
  File "/mnt/data/.virtualenvs/build_deploy/local/lib/python2.7/site-packages/dockermap/map/runner/cmd.py", line 54, in exec_container_commands
    self.exec_commands(config, c_name, run_cmds=config_cmds)
  File "/mnt/data/.virtualenvs/build_deploy/local/lib/python2.7/site-packages/dockermap/map/runner/cmd.py", line 37, in exec_commands
    e_id = client.exec_create(**ec_kwargs)['Id']
  File "/mnt/data/.virtualenvs/build_deploy/local/lib/python2.7/site-packages/dockerfabric/cli.py", line 122, in exec_create
    cmd_str = self._out.get_cmd('exec_create', *args, **kwargs)
TypeError: get_cmd() got multiple values for keyword argument 'cmd'
```

I've seen something similar before and assumed it was something wrong with my legacy code.  This time I seem to be using 100% internal functionality.

**Comment by merll** [comment]
``cmd`` is the first positional argument of ``get_cmd``, and conflicts with ``cmd`` used in ``exec_create``. This will be fixed in the next release.
