### ISSUE TITLE
python 3.x support

### ISSUE THREAD

**Issue by pahaz** [merll/docker-map#3]
Traceback (most recent call last):
      File "test_docker.py", line 3, in <module>
        from dockermap.build.dockerfile import DockerFile
      File "/venv/lib/python3.2/site-packages/dockermap/build/dockerfile.py", line 10, in <module>
        from .buffer import DockerStringBuffer
      File "/venv/lib/python3.2/site-packages/dockermap/build/buffer.py", line 5, in <module>
        import cStringIO
    ImportError: No module named cStringIO

**Comment by merll** [comment]
Fixed with #4. Thanks again for the PR.
